#!/usr/bin/env bash
#script to perform 301 moved permanently

sudo apt-get update
sudo apt-get install -y nginx
sudo mkdir /var/www/html
sudo touch /var/www/html/index.html

echo "Hello world!" | tee /var/www/html/index.html
string_replace="server_name _;\n\trewrite ^\/redirect_me http:\/\/github.com/pharmakarios1 permanent;"
sudo sed -i "s/server_name _;/$string_replace/" /etc/nginx/sites-enabled/default

sudo service nginx restart

